name: Compile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:

  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - uses: actions/checkout@v4

      - name: lzip
        run: sudo apt install -y lzip

      - id: check
        name: check
        run: node build.js | tee out.txt; echo "RESULT=$(tail out.txt -n 1)" >> $GITHUB_OUTPUT; rm out.txt

      - name: commit
        if: steps.check.outputs.RESULT == 'Done'
        uses: stefanzweifel/git-auto-commit-action@v5

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1